version: '3.9'

services:
  db:
    restart: unless-stopped
    container_name: postgres
    image: postgres:15-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'pg'
      POSTGRES_PASSWORD: 'pg'
      POSTGRES_DB: 'AD_INTEGRATION'
    ports:
      - "5432:5432"
    networks:
      net:
        ipv4_address: 10.5.0.2

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 3


  app:
    restart: unless-stopped
    build: ./app
    command: uvicorn --bind 0.0.0.0:8000 main:app
    volumes:
      - ./app/:/usr/src/app/

    expose:
      - 8000
    env_file:
      - ./.env

    networks:
      net:
        ipv4_address: 10.5.0.4

    depends_on:
      db:
        condition: service_healthy


  nginx:
    restart: unless-stopped
    build: ./nginx
    ports:
      - "1340:80"

    networks:
      net:
        ipv4_address: 10.5.0.5

    depends_on:
      - app

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "pg@rpz.ru"
      PGADMIN_DEFAULT_PASSWORD: "pg"
    ports:
      - "5055:80"
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 10.5.0.3

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16




