version: '3.9'

services:
  db:
    restart: unless-stopped
    container_name: ad_api_postgres
    image: postgres:15-bookworm
    env_file:
      - .env_non_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      net:
        ipv4_address: 11.6.1.2

  ad_api:
    restart: unless-stopped
    build:
      context: .
    container_name: ad_api_app
    networks:
      net:
        ipv4_address: 11.6.1.4
    depends_on:
      - db
    # command: ["ad_api/docker/app.sh"]
    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"

    #ports:
      #- "7777:8000"

  nginx:
   build:
     context: .
     dockerfile: "Dockerfile.nginx"
   container_name: ad_api_nginx
   ports:
    - 1380:80
    #- 1443:443
   links:
    - ad_api
    #- pgadmin

   restart: unless-stopped

   networks:
      net:
        ipv4_address: 11.6.1.5


  ad_api_pg_adm:
    container_name: ad_api_pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - .env_non_dev
    ports:
      - "5051:80"
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 11.6.1.3

    depends_on:
      - db


volumes:
  postgres_data:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 11.6.1.0/24




